//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Inscripcion_Cliente = new HashSet<Inscripcion_Cliente>();
            this.Numero_Contacto = new HashSet<Numero_Contacto>();
            this.Ticket_Tecnico = new HashSet<Ticket_Tecnico>();
            this.Ticket_Vista_Cliente = new HashSet<Ticket_Vista_Cliente>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nombre { get; set; }
        public string Documento { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<int> Cargo_ID { get; set; }
        public Nullable<int> Area_ID { get; set; }
        [JsonIgnore]
        public virtual Area Area { get; set; }
        [JsonIgnore]
        public virtual Cargo Cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Inscripcion_Cliente> Inscripcion_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Numero_Contacto> Numero_Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Ticket_Tecnico> Ticket_Tecnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Ticket_Vista_Cliente> Ticket_Vista_Cliente { get; set; }
    }
}
