//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion_Producto
    {
        public int ID_Inscripcion_Producto { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
