//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoporteEntities : DbContext
    {
        public SoporteEntities()
            : base("name=SoporteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<Inscripcion_Cliente> Inscripcion_Cliente { get; set; }
        public virtual DbSet<Inscripcion_Producto> Inscripcion_Producto { get; set; }
        public virtual DbSet<Login_Admin> Login_Admin { get; set; }
        public virtual DbSet<Login_Tecnico> Login_Tecnico { get; set; }
        public virtual DbSet<Numero_Contacto> Numero_Contacto { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Tecnico> Tecnicoes { get; set; }
        public virtual DbSet<Ticket_Tecnico> Ticket_Tecnico { get; set; }
        public virtual DbSet<Ticket_Vista_Cliente> Ticket_Vista_Cliente { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
    }
}
