//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Inscripcion_Producto = new HashSet<Inscripcion_Producto>();
        }
    
        public int ID_Producto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Modelo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Tipo { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Inscripcion_Producto> Inscripcion_Producto { get; set; }
        [JsonIgnore]
        public virtual Tipo_Producto Tipo_Producto { get; set; }
    }
}
