//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Tecnico
    {
        public int ID_Ticket_Tecnico { get; set; }
        public Nullable<int> ID_Tecnico { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Estado { get; set; }
        public string DescripcionProblema { get; set; }
        public string TipoSoporte { get; set; }
        public string ProductoSoporte { get; set; }
        public string DescripcionSolucion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
