//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupportEntities : DbContext
    {
        public SupportEntities()
            : base("name=SupportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addre> Addres { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Contact_Number> Contact_Number { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_User> Customer_User { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Number_Type> Number_Type { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Detail> Product_Detail { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Contact_Number> Supplier_Contact_Number { get; set; }
        public virtual DbSet<Support_Type> Support_Type { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<Technician_User> Technician_User { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Ticket_Detail> Ticket_Detail { get; set; }
        public virtual DbSet<Ticket_Status> Ticket_Status { get; set; }
    }
}
