//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Detail_ID { get; set; }
        public Nullable<System.DateTime> Date_Invoice { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Product_Detail Product_Detail { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
