//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Number_Type()
        {
            this.Contact_Number = new HashSet<Contact_Number>();
            this.Supplier_Contact_Number = new HashSet<Supplier_Contact_Number>();
        }
    
        public int Number_Type_ID { get; set; }
        public string Number_Type1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Number> Contact_Number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Contact_Number> Supplier_Contact_Number { get; set; }
    }
}
