//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Detail = new HashSet<Product_Detail>();
            this.Ticket_Detail = new HashSet<Ticket_Detail>();
        }
    
        public int Product_ID { get; set; }
        public Nullable<int> Product_Type_ID { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public string Serial { get; set; }
        public string Features { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Product_Type Product_Type { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Detail> Product_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Detail> Ticket_Detail { get; set; }
    }
}
