//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Contact_Number
    {
        public int Contact_Number_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public string Number { get; set; }
        public Nullable<int> Number_Type_ID { get; set; }
    
        public virtual Number_Type Number_Type { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
