//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician_User
    {
        public int Id_TechnicianUser { get; set; }
        public string Username { get; set; }
        public string Password_technician { get; set; }
        public Nullable<int> Technician_ID { get; set; }
    
        public virtual Technician Technician { get; set; }
    }
}
