//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Ticket_Detail = new HashSet<Ticket_Detail>();
        }
    
        public int Ticket_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Problem_Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Ticket_Status Ticket_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Detail> Ticket_Detail { get; set; }
    }
}
