//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Detail
    {
        public int Detail_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public Nullable<int> Technician_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Support_Type_ID { get; set; }
        public string Detail { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Support_Type Support_Type { get; set; }
        public virtual Technician Technician { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
